from typing import List


class _Tag:
    def find(self, tag: str = None, id: str = None, class_: str = None) -> '_Tag': ...
    def find_all(self, tag: str = None, class_: str = None) -> List['_Tag']: ...
    def __getitem__(self, attr: str) -> str: ...

class BeautifulSoup(_Tag):
    def __init__(self, html: str, parser: str = None) -> None: ...
