from typing import Dict, Any


class KernelClient:
    def execute(self, code: str) -> str: ...
    def shutdown(self) -> str: ...
    def get_shell_msg(self, timeout: int = None) -> Dict[str, Any]: ...
    def get_iopub_msg(self, timeout: int = None) -> Dict[str, Any]: ...
    def start_channels(self) -> None: ...


class KernelManager:
    def __init__(self, kernel_name: str = None) -> None: ...
    def start_kernel(self) -> None: ...
    def restart_kernel(self) -> None: ...
    def shutdown_kernel(self) -> None: ...
    def client(self) -> KernelClient: ...
