#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
from argparse import ArgumentParser
import webbrowser
import asyncio


def parse_cli() -> dict:
    parser = ArgumentParser()
    arg = parser.add_argument
    arg('source', metavar='FILE')
    arg('report', metavar='REPORT', nargs='?')
    arg('-b', '--browser', type=webbrowser.get, default=webbrowser.get())
    arg('-n', '--no-browser', dest='browser', action='store_false')
    return vars(parser.parse_args())


if __name__ == '__main__':
    kwargs = parse_cli()
    from neptune import Neptune
    task = asyncio.ensure_future(Neptune(**kwargs).run())
    try:
        asyncio.get_event_loop().run_until_complete(task)
    except KeyboardInterrupt:
        task.cancel()
        asyncio.get_event_loop().run_forever()
